@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ComponentActivity: onCreate
ComponentActivity -> ReportFragment: injectIfNeededIn
 -> ReportFragment: onCreate
ComponentActivity -> LifecycleRegistry: handleLifecycleEvent
activate LifecycleRegistry
LifecycleRegistry -> LifecycleRegistry: moveToState
LifecycleRegistry -> LifecycleRegistry: sync




'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response

'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
@enduml